### ISSUE TITLE
 Extension misinterprets reused types as recursive

### ISSUE THREAD

**Issue by datadrivensakura** [hannes/duckdb_avro#4]
### Introduction

When working with Avro schemas in DuckDB, certain patterns of type reuse can cause the Avro extension to incorrectly flag a schema as having recursive types. This issue arises even in valid Avro schemas that are not truly recursive. A named type that is defined once and then referenced in multiple fields should be acceptable; however, DuckDB’s Avro extension may mistake this reuse for recursion, preventing the schema from being loaded.

### Problem Description:

What Is Happening:
- Consider the following schema, which defines a Version record and uses it both inline (`client_version`) and by reference (`server_version`): 

```json
{
  "type": "record",
  "name": "Request",
  "namespace": "example.avro",
  "fields": [
    {
      "name": "request_id",
      "type": "string"
    },
    {
      "name": "client_version",
      "type": {
        "type": "record",
        "name": "Version",
        "fields": [
          {
            "name": "major",
            "type": "int"
          },
          {
            "name": "minor",
            "type": "int"
          }
        ]
      }
    },
    {
      "name": "server_version",
      "type": "Version"
    }
  ]
}
```

In this schema:
  - `Version` is defined once, as part of the `client_version` field.
  - `Version` is then reused by reference for `server_version`.

**Avro allows this pattern. The `Version` type does not reference itself, nor does `Request` or any sub-record recursively refer back to itself. This should not be considered recursive.**

- Why It’s Not Actually Recursive
Recursion would require a type to directly or indirectly reference itself. For example, a Node that has a field of type Node is recursive. Here, `Version` is merely being reused. There’s no cycle or self-reference, so it is not recursive by definition.

**Another Example (Top-Level and Deeper Level Reuse)**
```json
{
  "type": "record",
  "name": "Request",
  "namespace": "example.avro",
  "fields": [
    {
      "name": "version",
      "type": {
        "type": "record",
        "name": "Version",
        "fields": [
          { "name": "major", "type": "int" },
          { "name": "minor", "type": "int" }
        ]
      }
    },
    {
      "name": "details",
      "type": {
        "type": "record",
        "name": "Details",
        "fields": [
          { "name": "release_version", "type": "Version" }
        ]
      }
    }
  ]
}
```
In this example:

- `Version` is defined at the top level within `Request’s` fields.
- `Version` is then referenced again inside the nested `Details` record as `release_version`.

Just like the previous example, `Version` does not refer to itself. There is no path through the schema definitions that leads back to `Version` through `Version`. Instead,`Version` is simply the same structure reused at multiple levels. This is not recursive; it’s a straightforward reuse of a named type. Avro’s naming and referencing semantics are designed to allow this without implying recursion.

### Observed Error Message
When loading this schema into DuckDB using the Avro extension, you may encounter an error message like:

```sql
Invalid Input Error: Recursive Avro type Version not supported
```
This suggests that DuckDB believes `Version` is recursive, even though it’s not.

### DuckDB
Given the schemas, DuckDB should ideally represent them like this:

- Non-Recursive Reuse (First Example):
```sql
CREATE TABLE request
(
    request_id     STRING,
    client_version STRUCT(major INT, minor INT),
    server_version STRUCT(major INT, minor INT)
);
```

- Non-Recursive Reuse (Second Example):
```sql
CREATE TABLE request
(
    version STRUCT(major INT, minor INT),
    details STRUCT(release_version STRUCT(major INT, minor INT))
);
```
In both cases, the STRUCT definitions are reused without any circular dependency.

### Impact
Because reusing named types is a common pattern in Avro schemas, this issue can prevent users from loading valid Avro data into DuckDB. If a schema defines a record once and references it multiple times, users might be forced to rename or flatten their schemas unnecessarily. This not only complicates data ingestion but also increases maintenance overhead, working against a widely accepted Avro design practice.

**Comment by hannes** [comment]
This should work once https://github.com/duckdb/community-extensions/pull/242 is merged

**Comment by datadrivensakura** [comment]
@hannes I can confirm that it works as expected! Thank you so much!
